<?php
require_once('basic.php');

require_once('html/get_attlist.php');
require_once('html/title_tag.php');
require_once('html/head_tag.php');
require_once('html/body_tag.php');
require_once('html/page_title.php');
require_once('html/start_page_function.php');
require_once('html/default_end_page.php');
require_once('html/end_page_function.php');
require_once('html/anchor_tag.php');
require_once('html/font_tag.php');
require_once('html/image_tag.php');
require_once('html/start_paragraph.php');
require_once('html/end_paragraph.php');
require_once('html/paragraph.php');
require_once('html/subtitle.php');
require_once('html/li_tag.php');
require_once('html/ul_list.php');
require_once('html/table_cell.php');
require_once('html/table_row.php');
require_once('html/table_header_cell.php');
require_once('html/table_header_row.php');
require_once('html/end_table.php');
require_once('html/start_table.php');
require_once('html/table_function.php');
require_once('html/hashlist_table.php');
require_once('html/labeled_row.php');
?>
